---
- name: installing softwares to run cicd in ansible
  hosts: all
  tasks:
    - name: use apt
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
       - {a: openjdk-8-jdk,b: yes}
       - {a: git,b: no}
       - {a: maven,b: no}
       - {a: tomcat9,b: no}
       - {a: tomcat9-admin,b: no}
- name: perform cont.downloads & cont. build
  hosts: dev
  tasks:
    - name: git downloads the code
      git:
        repo: https://github.com/SAGARSGS/java_Project.git
        dest: /tmp/github1
...
